print("starting new menu (empty commands: close the menu)")
mn = input("menu name: ")
tln = input("top left name: ")
trn = input("top right name: ")
bln = input("bottom left name: ")
brn = input("bottom right name: ")
tlc = input("top left command: ")
trc = input("top right command: ")
blc = input("bottom left command: ")
brc = input("bottom right command: ")
print()
print("add the line below into the config list in main.py, then re-run make install as root")
print()
print('{ "menu-name":"%s", "top-left":{ "option-name":"%s", "command":"%s" }, "top-right":{ "option-name":"%s", "command":"%s" }, "bottom-left":{ "option-name":"%s", "command":"%s" }, "bottom-right":{ "option-name":"%s", "command":"%s" } }' % (mn, tln, tlc, trn, trc, bln, blc, brn, brc))
